    basketball_in_hoop: 0
    close_box: 10
    close_laptop_lid: 10
    empty_dishwasher: 0
    get_ice_from_fridge: 5
    hockey: 0
    meat_on_grill: 0
    move_hanger: 0
    wipe_desk: 0
    open_drawer: 5
    slide_block_to_target: 0
    reach_and_drag: 5
    put_money_in_safe: 5
    place_wine_at_rack_location: 0
    insert_onto_square_peg: 10
    stack_cups: 0
    turn_oven_on: 5
    straighten_rope: 10
    setup_chess: 5
    scoop_with_spatula: 5